" 默认进入目录
cd E:\workspace

" 关闭vi兼容
set nocompatible
           
" 解决中文乱码
set encoding=utf-8
set termencoding=utf-8
set fileencodings=utf-8,gbk,latin1

" gui模式配置
if has('gui_running') 
	" 隐藏菜单栏
	set guioptions-=m
	set guioptions-=T
	set guioptions-=r
	set guioptions-=L
	set guioptions-=b
	set showtabline=0

	" 更改菜单和提示语言为英语
	set langmenu=en_US
	let $LANG = 'en_US'
	source $VIMRUNTIME/delmenu.vim
	source $VIMRUNTIME/menu.vim

	" 设置窗口位置
	winpos 190 24
	" 设置初始窗口大小
	set lines=32 columns=110

	" 背景透明
	" autocmd guienter * call libcallnr('vimtweak.dll', 'SetAlpha', 222)
	" 全屏
	map <F11> :call libcallnr('gvimfullscreen.dll', 'ToggleFullScreen', 0)<CR>
	" 还原初始窗口
	map <F12> :set lines=32 columns=110 <Bar> winpos 190 24<CR>
endif

" 插件
call plug#begin('~/vimfiles/plugged')
Plug 'scrooloose/nerdtree'
Plug 'joshdick/onedark.vim'
Plug 'skywind3000/vim-terminal-help'
Plug 'vim-airline/vim-airline'
call plug#end()

" airline配置
let g:airline#extensions#tabline#enabled = 1
let g:airline#extensions#tabline#buffer_nr_show = 1
let g:airline#extensions#tabline#formatter = 'unique_tail'
let g:airline_section_z=''           " 隐藏倒数第二行显示的内容
let g:airline_section_error=''       " 隐藏倒数第一行显示的内容
let g:airline_section_warning=''     " 隐藏倒数第一行显示的内容
let g:airline_symbols_ascii = 1      " 隐藏图标

" 切换buffer快捷键
" nnoremap <tab> :bn<CR> " 下一个
" nnoremap <s-tab> :bp<CR> " 上一个
nnoremap <C-C> :bd<CR> " 关闭当前
" 切换buffer快捷键（airline提供的方法，可以忽略内置terminal）
nmap <s-tab> <Plug>AirlineSelectPrevTab
nmap <tab> <Plug>AirlineSelectNextTab

" 颜色主题
syntax on
syntax enable
set t_Co=256
" 可选主题
colorscheme onedark

" 设置字体
set guifont=Consolas:h11
" set guifontwide=SimSun-ExtB:h12 " 单独设置中文字体

" F2 文件目录
map <F2> :NERDTreeToggle<CR>
let NERDTreeShowBookmarks=1
let NERDTreeShowHidden=1 " 目录中显示隐藏文件

" F3 内置terminal
map <F3> :ter<CR>

" 插入模式光标移动配置
inoremap <C-h> <Left>
inoremap <C-j> <Down>
inoremap <C-k> <Up>
inoremap <C-l> <Right>
inoremap <C-d> <DELETE>

" 共享剪贴板
set clipboard+=unnamed
" 设置terminal粘贴系统剪贴板快捷键 alt + 0
tnoremap <m-0> <c-_>"*

" 搜索高亮显示
set hlsearch

" 显示行号
set number

" 根据打开文件切换对应路径
set autochdir

" 设置禁用错误提示音
set belloff=all

" 设置tab空格数
set nowrap
set backspace=indent,eol,start
set shiftwidth=4

" tab字符替换成4个空格
set expandtab
set tabstop=4

" 自动缩进
set smarttab
set autoindent
set smartindent
